version: "3.9"

services:

  mysql-dev:
    image: "mysql:8.0.2"
    environment: 
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
    ports: 
      - "3308:3306"
    volumes:
      - "./data802:/var/lib/mysql:rw"

  mysql-legacy:
    image: "mysql:5.7"
    environment: 
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
    ports: 
      - "3306:3306"
    volumes:
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./data57:/var/lib/mysql:rw"

  admin:
    image: adminer
    ports:
      - 8080:8080

